#!/usr/bin/env bash
#
# MFCBricklaying
# https://github.com/mfcbricklaying/mfcbricklaying.github.io
#

set -e

GIT_USERNAME="MFCBricklayingCIBot"
GIT_EMAIL="github+ci@mfcbricklaying.com.au"
GIT_URL="https://github.com/mfcbricklaying/mfcbricklaying.github.io.git"

echo "[CI] -> Configuring Git options..."
git config --global user.email "${GIT_EMAIL}"
git config --global user.name "${GIT_USERNAME}"
git remote set-url origin $GIT_URL

echo "[CI] -> Merging pull request..."
git remote set-branches --add origin master
git fetch
git reset --hard
git checkout master --force
git merge --no-ff --no-edit "${TRAVIS_COMMIT}"

git push origin master
if [ $? -eq 0 ]; then
  echo "[CI] -> Successfully merged pull-request into master"
else
  echo "[CI] -> Failed to merge pull-request into master" && exit 1
fi

echo "[CI] -> Done" && exit 0
